### ISSUE TITLE
`ColorModeScript` shows error on Next.js 14.2

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#1191]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.3

### Description

Using <ColorModeScript /> in `layout.tsx` with Next.js 14.2 shows error below when running `pnpm build` and `pnpm start`.

```
 ⨯ Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    at nM (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61599)
    at nM (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
    at nN (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
    at nB (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
    at nN (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
    at nB (/home/taroj1205/GitHub/nextjs-portfolio/node_modules/.pnpm/next@14.2.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538) {
  digest: '3674135139'
}
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

**Comment by taroj1205** [comment]
Fixed with Next.js update.
