### ISSUE TITLE
Error occurs when using `ScrollArea` in `Next.js`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1620]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.10

### Description

It's probably caused by using `useLayoutEffect`.

```log
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at eval (webpack-internal:///../packages/components/scroll-area/src/scroll-area.tsx:83:101)
    at Editor (webpack-internal:///./components/mdx/editable-code-block.tsx:384:19)
    at div
    at /Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../packages/core/src/styled.ts:49:95)
    at div
    at /Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../packages/core/src/styled.ts:49:95)
    at LiveProvider (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/react-live@4.1.6_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/react-live/dist/index.js:248:3)
    at EditableCodeBlock (webpack-internal:///./components/mdx/editable-code-block.tsx:169:30)
    at s (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_@opentelemetry+api@1.8.0_babel-plugin-macros@3.1.0_react-dom@1_fszec6o4cwtg3dlodsngxeq55u/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:2924)
    at CodeBlock (webpack-internal:///./components/mdx/code-block.tsx:32:22)
    at pre
    at pa (eval at getMDXComponent (file:///Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/next-contentlayer@0.3.4_contentlayer@0.3.4_esbuild@0.20.2_markdown-wasm@1.2.0__esbuild@0.20.2_v5y2ibxtuixx3hw3x2zezjnixq/node_modules/next-contentlayer/dist/hooks/useMDXComponent.js:9:16), <anonymous>:210:1178)
    at div
    at /Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../packages/core/src/styled.ts:49:95)
    at div
    at /Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../packages/core/src/styled.ts:49:95)
    at eval (webpack-internal:///../packages/components/layouts/src/stack.tsx:25:93)
    at eval (webpack-internal:///../packages/components/layouts/src/stack.tsx:97:83)
    at div
    at /Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../packages/core/src/styled.ts:49:95)
    at eval (webpack-internal:///../packages/components/layouts/src/stack.tsx:25:93)
    at eval (webpack-internal:///../packages/components/layouts/src/stack.tsx:82:83)
    at main
    at /Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../packages/core/src/styled.ts:49:95)
    at DocumentLayout (webpack-internal:///./layouts/document-layout.tsx:25:27)
    at PageProvider (webpack-internal:///./contexts/page-context.tsx:28:25)
    at Page (webpack-internal:///./pages/components/[[...slug]].page.tsx:25:17)
    at I18nProvider (webpack-internal:///./contexts/i18n-context.tsx:45:25)
    at LoadingProvider (webpack-internal:///../packages/components/loading/src/loading-provider.tsx:46:28)
    at MotionConfig (webpack-internal:///../node_modules/.pnpm/framer-motion@9.1.7_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/framer-motion/dist/es/components/MotionConfig/index.mjs:33:25)
    at EnvironmentProvider (webpack-internal:///../packages/providers/src/environment-provider.tsx:19:32)
    at ColorModeProvider (webpack-internal:///../packages/core/src/providers/color-mode-provider.tsx:24:41)
    at ThemeProvider (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/@emotion+react@11.11.0_@types+react@18.3.2_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:125:32)
    at ThemeProvider (webpack-internal:///../packages/core/src/providers/theme-provider.tsx:31:33)
    at UIProvider (webpack-internal:///../packages/providers/src/ui-provider.tsx:25:27)
    at App (webpack-internal:///./pages/_app.page.tsx:27:16)
    at StyleRegistry (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/styled-jsx@5.1.1_@babel+core@7.24.4_babel-plugin-macros@3.1.0_react@18.2.0/node_modules/styled-jsx/dist/index/index.js:449:36)
    at eU (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_@opentelemetry+api@1.8.0_babel-plugin-macros@3.1.0_react-dom@1_fszec6o4cwtg3dlodsngxeq55u/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:20468)
    at eH (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_@opentelemetry+api@1.8.0_babel-plugin-macros@3.1.0_react-dom@1_fszec6o4cwtg3dlodsngxeq55u/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:17:1765)
    at eJ (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_@opentelemetry+api@1.8.0_babel-plugin-macros@3.1.0_react-dom@1_fszec6o4cwtg3dlodsngxeq55u/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:17:3068)
    at div
    at e9 (/Users/hirotomoyamada/GitHub/hirotomoyamada/yamada-ui/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_@opentelemetry+api@1.8.0_babel-plugin-macros@3.1.0_react-dom@1_fszec6o4cwtg3dlodsngxeq55u/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:26:761)
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by sKawashima** [comment]
client hooks is not work in server compornent.
so please write `'use client'` on file of first

**Comment by hirotomoyamada** [comment]
@sKawashima 

This is a page router.

**Comment by hirotomoyamada** [comment]
```diff
- useLayoutEffect(() => {
+ useSafeLayoutEffect(() => {
  if (!scrollAreaRef.current || !isSafari) return

  scrollAreaRef.current.scrollLeft = scrollPosition.current.x
  scrollAreaRef.current.scrollTop = scrollPosition.current.y
})
```
