### ISSUE TITLE
React does not recognize the `isFitContent` prop on a DOM element.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1681]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.12

### Description

React does not recognize the `isFitContent` prop on a DOM element.

```log
Warning: React does not recognize the `isFitContent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isfitcontent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-RLY4AXQN.js?v=ee03d05b:148:45
    at http://localhost:6006/packages/core/src/styled.ts:38:35
    at http://localhost:6006/packages/components/skeleton/src/skeleton-text.tsx:8:5
    at section
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-RLY4AXQN.js?v=ee03d05b:148:45
    at http://localhost:6006/packages/core/src/styled.ts:38:35
    at http://localhost:6006/packages/components/layouts/src/container.tsx:11:33
    at App (http://localhost:6006/.storybook/components.tsx:24:16)
    at LoadingProvider (http://localhost:6006/packages/components/loading/src/loading-provider.tsx:42:3)
    at MotionConfig (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/framer-motion.js?v=ee03d05b:6985:25)
    at EnvironmentProvider (http://localhost:6006/packages/providers/src/environment-provider.tsx:10:3)
    at ColorModeProvider (http://localhost:6006/packages/core/src/providers/color-mode-provider.tsx:17:14)
    at ThemeProvider2 (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-RLY4AXQN.js?v=ee03d05b:195:21)
    at ThemeProvider (http://localhost:6006/packages/core/src/providers/theme-provider.tsx:20:10)
    at UIProvider (http://localhost:6006/packages/providers/src/ui-provider.tsx:14:3)
    at StoryProvider (http://localhost:6006/.storybook/components.tsx:13:33)
    at unboundStoryFn (http://localhost:6006/sb-preview/runtime.js:113:5798)
    at ErrorBoundary (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-PGXUOQQT.js?v=ee03d05b:32:5)
    at WithCallback (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-SDSMAM74.js?v=ee03d05b:15:23)
```

### Steps to Reproduce

1. Set `isFitContent` to `SkeletonText`.
2. See error

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

```diff
- export type SkeletonTextProps = SkeletonProps & SkeletonTextOptions
+ export type SkeletonTextProps = Omit<SkeletonProps, "isFitContent"> & SkeletonTextOptions
```

**Comment by yasuaki640** [comment]
Hello @hirotomoyamada.
Can I work on this issue?

**Comment by hirotomoyamada** [comment]
@yasuaki640 

Hi, thanks for the comment!

Yes, pls.
