### ISSUE TITLE
`@yamada-ui/theme` need `"use client"` to use `loading.tsx` in Next.js 15

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#3331]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.6.1

### Description

`@yamada-ui/theme` need `"use client"` to use `loading.tsx` in Next.js 15.

`loading.tsx`
```tsx
import { Center, Loading } from "@yamada-ui/react"

export default function LoadingPage() {
  return (
    <Center>
      <Loading />
    </Center>
  )
}
```

This error has occurred.
```cmd
> yamada-ui-custom@0.1.0 dev G:\workspace\playground\yamada-ui-custom
> next dev --turbopack

   ▲ Next.js 15.0.2 (Turbopack)
   - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1260ms
 ○ Compiling / ...
 ✓ Compiled / in 5.2s
 ⨯ Error: Attempted to call mergeMultiStyle() from the server but mergeMultiStyle is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
    at <unknown> (turbopack://[project]/node_modules/.pnpm/@yamada-ui+core@1.6.4_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028_xhwdjspfjs2lcpye2sqkckdrzi/node_modules/@yamada-ui/core/dist/index.mjs/proxy.js:143:23)
    at [project]/node_modules/.pnpm/@yamada-ui+theme@1.5.5_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-2024102_pimnmpwdiv3lt2xnur7nntpwd4/node_modules/@yamada-ui/theme/dist/chunk-V7Q5NJUV.mjs [app-rsc] (ecmascript) (turbopack://[project]/node_modules/.pnpm/@yamada-ui+theme@1.5.5_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-2024102_pimnmpwdiv3lt2xnur7nntpwd4/node_modules/@yamada-ui/theme/src/components/alpha-slider.ts:5:48)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/@yamada-ui+theme@1.5.5_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-2024102_pimnmpwdiv3lt2xnur7nntpwd4/node_modules/@yamada-ui/theme/dist/chunk-4TO3VMEM.mjs [app-rsc] (ecmascript) (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\aa22d_@yamada-ui_theme_dist_7c4a85._.js:7751:378)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/@yamada-ui+theme@1.5.5_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-2024102_pimnmpwdiv3lt2xnur7nntpwd4/node_modules/@yamada-ui/theme/dist/index.mjs [app-rsc] (ecmascript) (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\aa22d_@yamada-ui_theme_dist_7c4a85._.js:8789:378)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/@yamada-ui+react@1.3.5_@emotion+react@11.11.4_react@19.0.0-rc-02c0e824-20241028_types-react@1_fdybiettvxxwe4bif23taxnggm/node_modules/@yamada-ui/react/dist/index.mjs [app-rsc] (ecmascript) <exports> (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\fbf17_@yamada-ui_react_dist_index_mjs_0f7ded._.js:263:366)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/src/app/loading.tsx [app-rsc] (ecmascript) (turbopack://[project]/src/app/loading.tsx:1:0)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/src/app/loading.tsx [app-rsc] (ecmascript, Next.js server component) (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\src_app_loading_tsx_1f4435._.js:33:32)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_1 => "[project]/src/app/loading.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <module evaluation> (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\_c317d0._.js:141:161)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_1 => "[project]/src/app/loading.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\_c317d0._.js:240:1301)
    at instantiateModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at instantiateRuntimeModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:652:12)
    at Object.getOrInstantiateRuntimeModule (G:\workspace\playground\yamada-ui-custom\.next\server\chunks\ssr\[turbopack]_runtime.js:668:12)
    at Object.<anonymous> (G:\workspace\playground\yamada-ui-custom\.next\server\app\page.js:14:26)
    at call (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/require-hook.ts:70:25)
    at require (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/require.ts:121:8)
    at page (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/load-components.ts:189:41)
    at async DevServer.findPageComponentsImpl (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/next-server.ts:777:27)
    at async DevServer.findPageComponents (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/dev/next-dev-server.ts:881:13)
    at async DevServer.renderPageComponent (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/base-server.ts:3663:19)
    at async DevServer.renderToResponseImpl (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/base-server.ts:3738:23)
    at async DevServer.pipeImpl (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/base-server.ts:1738:20)
    at async NextNodeServer.handleCatchallRenderRequest (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/next-server.ts:1032:6)
    at async DevServer.handleRequestImpl (file:///G:/workspace/playground/yamada-ui-custom/node_modules/.pnpm/next@15.0.2_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028__react@19.0.0-rc-02c0e824-20241028/node_modules/next/src/server/base-server.ts:1498:8)
  141 | );
  142 | export const mergeMultiStyle = registerClientReference(
> 143 |     function() { throw new Error("Attempted to call mergeMultiStyle() from the server but mergeMultiStyle is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component."); },
      |                       ^
  144 |     "[project]/node_modules/.pnpm/@yamada-ui+core@1.6.4_react-dom@19.0.0-rc-02c0e824-20241028_react@19.0.0-rc-02c0e824-20241028_xhwdjspfjs2lcpye2sqkckdrzi/node_modules/@yamada-ui/core/dist/index.mjs <module evaluation>",
  145 |     "mergeMultiStyle",
  146 | ); {
  page: '/'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 910ms
 GET / 500 in 6603ms
```

### Link to Reproduction

https://github.com/108yen/yamada-ui-custom/tree/639e725b4d67d7798ec411aecac816ea035b9eac

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

Works correctly to add `"use client"` in `loading.tsx`.

**Comment by hirotomoyamada** [comment]
If you want to provide customized themes to providers, you need to add `"use client"` to the file calling `UIProvider`.

Have you tried this?

**Comment by 108yen** [comment]
@hirotomoyamada 
Yes.
Even if add `"use client"` in `layout.tsx`, this error occured.

**Comment by hirotomoyamada** [comment]
@108yen 

Hmmm, it's a mystery...
